//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.08 at 11:54:51 AM EEST 
//


package com.ibm.filenet.deployment.operations;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Pair" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}SourceDeployDataSet"/>
 *         &lt;element ref="{}ConvertedDeployDataSet"/>
 *       &lt;/all>
 *       &lt;attribute name="deleteDestinationFilesOnError" type="{}boolean" default="true" />
 *       &lt;attribute name="useStoragePolicyMap" type="{}boolean" default="false" />
 *       &lt;attribute name="useStorageAreaMap" type="{}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "ConvertDeployDataSet")
public class ConvertDeployDataSet implements IOperation {

    @XmlElement(name = "Pair", required = true)
    protected String pair;
    @XmlElement(name = "SourceDeployDataSet", required = true)
    protected String sourceDeployDataSet;
    @XmlElement(name = "ConvertedDeployDataSet", required = true)
    protected String convertedDeployDataSet;
    @XmlAttribute(name = "deleteDestinationFilesOnError")
    protected String deleteDestinationFilesOnError;
    @XmlAttribute(name = "useStoragePolicyMap")
    protected String useStoragePolicyMap;
    @XmlAttribute(name = "useStorageAreaMap")
    protected String useStorageAreaMap;

    /**
     * Gets the value of the pair property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPair() {
        return pair;
    }

    /**
     * Sets the value of the pair property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPair(String value) {
        this.pair = value;
    }

    /**
     * Gets the value of the sourceDeployDataSet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceDeployDataSet() {
        return sourceDeployDataSet;
    }

    /**
     * Sets the value of the sourceDeployDataSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceDeployDataSet(String value) {
        this.sourceDeployDataSet = value;
    }

    /**
     * Gets the value of the convertedDeployDataSet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConvertedDeployDataSet() {
        return convertedDeployDataSet;
    }

    /**
     * Sets the value of the convertedDeployDataSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConvertedDeployDataSet(String value) {
        this.convertedDeployDataSet = value;
    }

    /**
     * Gets the value of the deleteDestinationFilesOnError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeleteDestinationFilesOnError() {
        if (deleteDestinationFilesOnError == null) {
            return "true";
        } else {
            return deleteDestinationFilesOnError;
        }
    }

    /**
     * Sets the value of the deleteDestinationFilesOnError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeleteDestinationFilesOnError(String value) {
        this.deleteDestinationFilesOnError = value;
    }

    /**
     * Gets the value of the useStoragePolicyMap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseStoragePolicyMap() {
        if (useStoragePolicyMap == null) {
            return "false";
        } else {
            return useStoragePolicyMap;
        }
    }

    /**
     * Sets the value of the useStoragePolicyMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseStoragePolicyMap(String value) {
        this.useStoragePolicyMap = value;
    }

    /**
     * Gets the value of the useStorageAreaMap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseStorageAreaMap() {
        if (useStorageAreaMap == null) {
            return "false";
        } else {
            return useStorageAreaMap;
        }
    }

    /**
     * Sets the value of the useStorageAreaMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseStorageAreaMap(String value) {
        this.useStorageAreaMap = value;
    }

}
