//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.08 at 11:54:51 AM EEST 
//


package com.ibm.filenet.deployment.operations;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Environment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeployDataSet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeployPackage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *       &lt;attribute name="overwritePackage" type="{}boolean" />
 *       &lt;attribute name="includeHalfMaps" type="{}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "CreateDeployPackage")
public class CreateDeployPackage {

    @XmlElement(name = "Environment", required = true)
    protected String environment;
    @XmlElement(name = "DeployDataSet", required = true)
    protected String deployDataSet;
    @XmlElement(name = "DeployPackage", required = true)
    protected String deployPackage;
    @XmlAttribute(name = "overwritePackage")
    protected String overwritePackage;
    @XmlAttribute(name = "includeHalfMaps")
    protected String includeHalfMaps;

    /**
     * Gets the value of the environment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnvironment() {
        return environment;
    }

    /**
     * Sets the value of the environment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnvironment(String value) {
        this.environment = value;
    }

    /**
     * Gets the value of the deployDataSet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeployDataSet() {
        return deployDataSet;
    }

    /**
     * Sets the value of the deployDataSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeployDataSet(String value) {
        this.deployDataSet = value;
    }

    /**
     * Gets the value of the deployPackage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeployPackage() {
        return deployPackage;
    }

    /**
     * Sets the value of the deployPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeployPackage(String value) {
        this.deployPackage = value;
    }

    /**
     * Gets the value of the overwritePackage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverwritePackage() {
        return overwritePackage;
    }

    /**
     * Sets the value of the overwritePackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverwritePackage(String value) {
        this.overwritePackage = value;
    }

    /**
     * Gets the value of the includeHalfMaps property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludeHalfMaps() {
        return includeHalfMaps;
    }

    /**
     * Sets the value of the includeHalfMaps property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludeHalfMaps(String value) {
        this.includeHalfMaps = value;
    }

}
