//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.08 at 11:54:51 AM EEST 
//


package com.ibm.filenet.deployment.operations;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AuditFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AuditReport">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="detailed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "auditFile",
    "auditReport"
})
@XmlRootElement(name = "GenerateAuditReport")
public class GenerateAuditReport implements IOperation {

    @XmlElement(name = "AuditFile", required = true)
    protected String auditFile;
    @XmlElement(name = "AuditReport", required = true)
    protected GenerateAuditReport.AuditReport auditReport;

    /**
     * Gets the value of the auditFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuditFile() {
        return auditFile;
    }

    /**
     * Sets the value of the auditFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuditFile(String value) {
        this.auditFile = value;
    }

    /**
     * Gets the value of the auditReport property.
     * 
     * @return
     *     possible object is
     *     {@link GenerateAuditReport.AuditReport }
     *     
     */
    public GenerateAuditReport.AuditReport getAuditReport() {
        return auditReport;
    }

    /**
     * Sets the value of the auditReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenerateAuditReport.AuditReport }
     *     
     */
    public void setAuditReport(GenerateAuditReport.AuditReport value) {
        this.auditReport = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="detailed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class AuditReport {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "detailed")
        protected Boolean detailed;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the detailed property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isDetailed() {
            return detailed;
        }

        /**
         * Sets the value of the detailed property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setDetailed(Boolean value) {
            this.detailed = value;
        }

    }

}
