//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.08 at 11:54:51 AM EEST 
//


package com.ibm.filenet.deployment.operations;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Pair" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *       &lt;attribute ref="{}type use="required""/>
 *       &lt;attribute name="mapStoragePolicies" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mapStorageAreas" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "MapData")
public class MapData implements IOperation {

    @XmlElement(name = "Pair", required = true)
    protected String pair;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "mapStoragePolicies")
    protected String mapStoragePolicies;
    @XmlAttribute(name = "mapStorageAreas")
    protected String mapStorageAreas;

    /**
     * Gets the value of the pair property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPair() {
        return pair;
    }

    /**
     * Sets the value of the pair property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPair(String value) {
        this.pair = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the mapStoragePolicies property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMapStoragePolicies() {
        return mapStoragePolicies;
    }

    /**
     * Sets the value of the mapStoragePolicies property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMapStoragePolicies(String value) {
        this.mapStoragePolicies = value;
    }

    /**
     * Gets the value of the mapStorageAreas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMapStorageAreas() {
        return mapStorageAreas;
    }

    /**
     * Sets the value of the mapStorageAreas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMapStorageAreas(String value) {
        this.mapStorageAreas = value;
    }

}
