//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.08 at 11:54:51 AM EEST 
//


package com.ibm.filenet.deployment.operations;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.ibm.filenet.deployment.xml.SourceObjectStores;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="SourceEnvironment">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DestinationEnvironment">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}SourceObjectStores"/>
 *       &lt;/all>
 *       &lt;attribute name="action" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="removeReassignedAssetsFromSource" type="{}boolean" default="false" />
 *       &lt;attribute name="includeRelatedIsolatedRegionsAndEventExportStores" type="{}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "ReassignObjectStore")
public class ReassignObjectStore implements IOperation {

    @XmlElement(name = "SourceEnvironment", required = true)
    protected ReassignObjectStore.SourceEnvironment sourceEnvironment;
    @XmlElement(name = "DestinationEnvironment", required = true)
    protected ReassignObjectStore.DestinationEnvironment destinationEnvironment;
    @XmlElement(name = "SourceObjectStores", required = true)
    protected SourceObjectStores sourceObjectStores;
    @XmlAttribute(name = "action")
    protected String action;
    @XmlAttribute(name = "removeReassignedAssetsFromSource")
    protected String removeReassignedAssetsFromSource;
    @XmlAttribute(name = "includeRelatedIsolatedRegionsAndEventExportStores")
    protected String includeRelatedIsolatedRegionsAndEventExportStores;

    /**
     * Gets the value of the sourceEnvironment property.
     * 
     * @return
     *     possible object is
     *     {@link ReassignObjectStore.SourceEnvironment }
     *     
     */
    public ReassignObjectStore.SourceEnvironment getSourceEnvironment() {
        return sourceEnvironment;
    }

    /**
     * Sets the value of the sourceEnvironment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReassignObjectStore.SourceEnvironment }
     *     
     */
    public void setSourceEnvironment(ReassignObjectStore.SourceEnvironment value) {
        this.sourceEnvironment = value;
    }

    /**
     * Gets the value of the destinationEnvironment property.
     * 
     * @return
     *     possible object is
     *     {@link ReassignObjectStore.DestinationEnvironment }
     *     
     */
    public ReassignObjectStore.DestinationEnvironment getDestinationEnvironment() {
        return destinationEnvironment;
    }

    /**
     * Sets the value of the destinationEnvironment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReassignObjectStore.DestinationEnvironment }
     *     
     */
    public void setDestinationEnvironment(ReassignObjectStore.DestinationEnvironment value) {
        this.destinationEnvironment = value;
    }

    /**
     * Gets the value of the sourceObjectStores property.
     * 
     * @return
     *     possible object is
     *     {@link SourceObjectStores }
     *     
     */
    public SourceObjectStores getSourceObjectStores() {
        return sourceObjectStores;
    }

    /**
     * Sets the value of the sourceObjectStores property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceObjectStores }
     *     
     */
    public void setSourceObjectStores(SourceObjectStores value) {
        this.sourceObjectStores = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        if (action == null) {
            return "0";
        } else {
            return action;
        }
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the removeReassignedAssetsFromSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoveReassignedAssetsFromSource() {
        if (removeReassignedAssetsFromSource == null) {
            return "false";
        } else {
            return removeReassignedAssetsFromSource;
        }
    }

    /**
     * Sets the value of the removeReassignedAssetsFromSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoveReassignedAssetsFromSource(String value) {
        this.removeReassignedAssetsFromSource = value;
    }

    /**
     * Gets the value of the includeRelatedIsolatedRegionsAndEventExportStores property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludeRelatedIsolatedRegionsAndEventExportStores() {
        if (includeRelatedIsolatedRegionsAndEventExportStores == null) {
            return "false";
        } else {
            return includeRelatedIsolatedRegionsAndEventExportStores;
        }
    }

    /**
     * Sets the value of the includeRelatedIsolatedRegionsAndEventExportStores property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludeRelatedIsolatedRegionsAndEventExportStores(String value) {
        this.includeRelatedIsolatedRegionsAndEventExportStores = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class DestinationEnvironment {

        @XmlElement(name = "Name", required = true)
        protected String name;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class SourceEnvironment {

        @XmlElement(name = "Name", required = true)
        protected String name;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
