//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.08 at 11:54:51 AM EEST 
//


package com.ibm.filenet.deployment.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="DestinationDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ExternalContentDestinationDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "CEConvertDestination")
public class CEConvertDestination {

    @XmlElement(name = "DestinationDirectory", required = true)
    protected String destinationDirectory;
    @XmlElement(name = "ExternalContentDestinationDirectory", required = true)
    protected String externalContentDestinationDirectory;

    /**
     * Gets the value of the destinationDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationDirectory() {
        return destinationDirectory;
    }

    /**
     * Sets the value of the destinationDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationDirectory(String value) {
        this.destinationDirectory = value;
    }

    /**
     * Gets the value of the externalContentDestinationDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalContentDestinationDirectory() {
        return externalContentDestinationDirectory;
    }

    /**
     * Sets the value of the externalContentDestinationDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalContentDestinationDirectory(String value) {
        this.externalContentDestinationDirectory = value;
    }

}
