//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.08 at 11:54:51 AM EEST 
//


package com.ibm.filenet.deployment.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ExportDescriptorFileName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "PEExportXML")
public class PEExportXML {

    @XmlElement(name = "ExportDescriptorFileName", required = true)
    protected Object exportDescriptorFileName;

    /**
     * Gets the value of the exportDescriptorFileName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getExportDescriptorFileName() {
        return exportDescriptorFileName;
    }

    /**
     * Sets the value of the exportDescriptorFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setExportDescriptorFileName(Object value) {
        this.exportDescriptorFileName = value;
    }

}
