//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.08 at 11:54:51 AM EEST 
//


package com.ibm.filenet.deployment.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="AnalysisReportFileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *       &lt;attribute name="generateDetailedReport" type="{}boolean" default="false" />
 *       &lt;attribute name="viewReportAfterProcessing" type="{}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "ValidationOutput")
public class ValidationOutput {

    @XmlElement(name = "AnalysisReportFileName", required = true)
    protected String analysisReportFileName;
    @XmlAttribute(name = "generateDetailedReport")
    protected String generateDetailedReport;
    @XmlAttribute(name = "viewReportAfterProcessing")
    protected String viewReportAfterProcessing;

    /**
     * Gets the value of the analysisReportFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnalysisReportFileName() {
        return analysisReportFileName;
    }

    /**
     * Sets the value of the analysisReportFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnalysisReportFileName(String value) {
        this.analysisReportFileName = value;
    }

    /**
     * Gets the value of the generateDetailedReport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerateDetailedReport() {
        if (generateDetailedReport == null) {
            return "false";
        } else {
            return generateDetailedReport;
        }
    }

    /**
     * Sets the value of the generateDetailedReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerateDetailedReport(String value) {
        this.generateDetailedReport = value;
    }

    /**
     * Gets the value of the viewReportAfterProcessing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewReportAfterProcessing() {
        if (viewReportAfterProcessing == null) {
            return "true";
        } else {
            return viewReportAfterProcessing;
        }
    }

    /**
     * Sets the value of the viewReportAfterProcessing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewReportAfterProcessing(String value) {
        this.viewReportAfterProcessing = value;
    }

}
